#!/usr/bin/env node

var dir = (process.argv[2] ? require('path').resolve(process.argv[2]) : process.cwd());
var port = process.argv[3] || 3000;
var location = process.argv[4] || 'D:/Apache24/bin/httpd';


var parseError = false;
try {
  var port = parseInt(port, 10);
} catch (e) {
  parseError = true;
}

if (parseError || port == null || typeof port !== 'number' || port < 0 || port > 70000) {
  throw 'the second command line arg, if present, should be a port number.\n Example: pache . 2000';
}

console.log('pache ' + (process.argv[2] || '.') + ' ' + port);
console.log(
  'Running apache at ' + dir + ' (' + process.argv[2] + ') on port ' + port
);

//full httpd docs: http://httpd.apache.org/docs/2.4/programs/httpd.html
var httpd = require('child_process').exec(
location + /* Without sudo it fails:
                         (13)Permission denied: make_sock: could not bind to address [::]:80
                         (13)Permission denied: make_sock: could not bind to address 0.0.0.0:80
                         no listening sockets available, shutting down
                         Unable to open logs */
' -c "DocumentRoot ' + dir  + '"' +
' -c "Listen '       + port + '"' +
' -c "AccessFileName .htaccess"'     + 
' -c "ErrorLog D:/Apache24/logs/pache.log"'         + // send logs to terminal
' -c "CustomLog D:/Apache24/logs/pache.log common"' +
' -e info'                           + // Set LogLevel http://httpd.apache.org/docs/2.4/mod/core.html#loglevel

// Without this.. "httpd: Could not reliably determine the server's fully qualified domain name, using MBP018-RWC.local for ServerName"
' -c "ServerName localhost"' +
' -D FOREGROUND');

httpd.stdout.on('data', function httpdStdout(data) {
  console.log(data);
});

httpd.stderr.on('data', function httpdStderr(data) {
  console.log(data);
});

httpd.on('close', function httpdClose(code) {
  console.log('httpd process exited with code ' + code);
});
